- name: install node and npm
  yum:
    name: [ 'nodejs', 'npm' ]
    state: installed
  
- name: create nodejs path
  file: 
    path: /var/nodejs
    state: directory

- name: copy nodejs backend logic
  copy:
    src: nodeJS_server
    dest: /var/nodejs/

- name: cd to nodejs directory and install npm modules
  command: chdir=/var/nodejs/nodeJS_server/ npm install

- name: "Install forever (to run Node.js app)."
  npm: name=forever global=yes state=present

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "Start Node.js app."
  command: forever start '/var/nodejs/nodeJS_server/index.js'
  when: "forever_list.stdout.find('/var/nodejs/nodeJS_server/index.js') == -1"
