- name: add mongo repository
  copy:
    src: mongodb-org.repo
    dest: /etc/yum.repos.d/

- name: install mongodb
  yum:
    name: mongodb-org
    state: present

- name: change mongo configuration
  copy:
    src: mongod.conf
    dest: /etc/mongod.conf

- name: changing the conf file ownership
  file:
    path: /etc/mongod.conf
    owner: mongod
    group: mongod
    mode: 0644

- name: restart mongodb
  service:
    name: mongod
    state: restarted
